config/routes.rb
Rails.application.routes.draw do

  resources :playlists do
      resources :songs
  end

  root 'playlists#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  validates :name, :date, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :playlist
  validates :title,  :album, :artist, :link_to_spotify, :link_to_youtube, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :date)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
  @playlist = Playlist.find(params[:playlist_id])
   @song = @playlist.songs.create(song_params)

   redirect_to playlist_path(@playlist)
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :album, :artist, :link_to_youtube, :link_to_spotify)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaylistToday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="nav">
    <div class="nav-left">
      <a class="nav-item is-brand" href="#">
        <img src="/images/logo.gif" alt="Bulma logo" max-height:"40">
      </a>
    </div>

  </nav>
<div class="container">
<%= yield %>
</div>
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>HAVAS</strong> by <a href="http://jgthms.com">Web Developer</a>. HAVAS 2016. The website content.
      </p>
      <p>
        <a class="icon" href="https://github.com/jgthms/bulma">
          <i class="fa fa-github"></i>
        </a>
      </p>
    </div>
  </div>
</footer>

</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="columns">
  <div class="column is-one-quarter">


      <div class="field">
        <%= f.label :name, class:"label" %><br>
        <%= f.text_field :name, class:"input is-danger" %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>
      <div class="actions">
        <%= f.submit class:"button is-primary " %>
      </div>
    <% end %>

  </div>
  <div class="column">

  </div>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title is-1">Listing Playlists </h1>
<h2 class="subtitle">by Havas</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.date %></td>
        <td><%= link_to 'Show', playlist,class:"button is-success" %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) ,class:"button is-primary"%></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, class:"button is-danger", data: { confirm: 'Are you sure?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path,class:"button is-primary" %>

app/views/playlists/new.html.erb
<h1 class="title is-1">New Playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title is-1">LISTS SONGS </h1>
<h1 class="subtitle ">   <strong>Name playlist:</strong> <%= @playlist.name %></h1>

<p class="espace-bottom">
  <strong>Date:</strong>
  <%= @playlist.date %>
</p>


<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artits</th>
      <th>link_youtube</th>
      <th>link_spotify</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlist.songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.album %></td>
        <td><%= song.artist %></td>
        <td><%= song.link_to_youtube %></td>
        <td><%= song.link_to_spotify %></td>

    <% end %>
  </tbody>
</table>

<div class="columns">
  <div class="column is-one-quarter">
    <h1 class="title is-2">Add a Song:</h1>
    <%= form_for([@playlist, @playlist.songs.build]) do |f| %>
      <p class="control has-icon has-icon-right">
        <%= f.label :title%><br>
        <%= f.text_field :title, class:"input is-danger"  %>
      </p>
      <p>
        <%= f.label :album %><br>
        <%= f.text_field :album, class:"input is-danger"  %>
      </p>
      <p>
        <%= f.label :artist %><br>
        <%= f.text_field  :artist , class:"input is-danger"%>
      </p>
      <p>
        <%= f.label :link_to_youtube %><br>
        <%= f.text_field  :link_to_youtube , class:"input is-danger"%>
      </p>
      <p>
        <%= f.label :link_to_spotify %><br>
        <%= f.text_field  :link_to_spotify , class:"input is-danger"%>
      </p>



      <p class="margen-in-buttom ">
        <%= f.submit class:"button is-primary "%>
      </p>
    <% end %>

    <%= link_to 'Edit Playlist', edit_playlist_path(@playlist), class:"button is-active" %> |
    <%= link_to 'Back to index', playlists_path, class:"button is-active" %>
  </div>
  <div class="column">

  </div>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.album %></td>
        <td><%= song.artist %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>